# DataFrame class

In [1]:
# dataframe도  마찬가지로 class

In [34]:
import numpy as np
import pandas as pd

## 데이터프레임 생성

In [37]:
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index, columns=columns)
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [21]:
df.지역.values

array(['수도권', '경상권', '수도권', '경상권'], dtype=object)

In [14]:
data = np.arange(24).reshape(4,6)
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index, columns=columns)
df

지역  2015  2010  2005  2000  2010-2015 증가율
서울   0     1     2     3     4              5
부산   6     7     8     9    10             11
인천  12    13    14    15    16             17
대구  18    19    20    21    22             23

In [20]:
df.values

array([['수도권', 9904312, 9631482, 9762546, 9853972, 0.0283],
       ['경상권', 3448737, 3393191, 3512547, 3655437, 0.0163],
       ['수도권', 2890451, 2632035, 2517680, 2466338, 0.0982],
       ['경상권', 2466052, 2431774, 2456016, 2473990, 0.0141]], dtype=object)

In [22]:
df['2015'].values

array([9904312, 3448737, 2890451, 2466052])

In [23]:
df.columns

Index(['지역', '2015', '2010', '2005', '2000', '2010-2015 증가율'], dtype='object')

In [42]:
df.index.name= '도시'
df.columns.name= '특성'
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율  2020
도시                                                              
서울  수도권  9904312  9631482  9762546  9853972         0.0283     1
부산  경상권  3448737  3393191  3512547  3655437         0.0163     2
인천  수도권  2890451  2632035  2517680  2466338         0.0982     3
대구  경상권  2466052  2431774  2456016  2473990         0.0141     4

In [26]:
# 전치
df.T

도시                  서울       부산       인천       대구
특성                                               
지역                 수도권      경상권      수도권      경상권
2015           9904312  3448737  2890451  2466052
2010           9631482  3393191  2632035  2431774
2005           9762546  3512547  2517680  2456016
2000           9853972  3655437  2466338  2473990
2010-2015 증가율   0.0283   0.0163   0.0982   0.0141

## 열 데이터의 갱신, 추가, 삭제

In [27]:
# 데이터 프레임은 열을 우선

In [43]:
df['2010-2015 증가율'] = df['2010-2015 증가율'] * 100
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율  2020
도시                                                              
서울  수도권  9904312  9631482  9762546  9853972           2.83     1
부산  경상권  3448737  3393191  3512547  3655437           1.63     2
인천  수도권  2890451  2632035  2517680  2466338           9.82     3
대구  경상권  2466052  2431774  2456016  2473990           1.41     4

In [44]:
df['2020'] = [1,2,3,4]
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율  2020
도시                                                              
서울  수도권  9904312  9631482  9762546  9853972           2.83     1
부산  경상권  3448737  3393191  3512547  3655437           1.63     2
인천  수도권  2890451  2632035  2517680  2466338           9.82     3
대구  경상권  2466052  2431774  2456016  2473990           1.41     4

In [45]:
del df['2020']
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82
대구  경상권  2466052  2431774  2456016  2473990           1.41

# 열 인덱싱

In [46]:
df['지역']      # 결과는 Series

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: object

In [48]:
df[['지역', '2015']]        # 두 개를 꺼내면 결과는 DataFrame

특성   지역     2015
도시              
서울  수도권  9904312
부산  경상권  3448737
인천  수도권  2890451
대구  경상권  2466052

In [49]:
df[['지역']]        # 결과는 DataFrame

특성   지역
도시     
서울  수도권
부산  경상권
인천  수도권
대구  경상권

In [52]:
type(df['지역']),type(df[['지역']])     # 왼쪽은 Series, 오른쪽은 DataFrame

(pandas.core.series.Series, pandas.core.frame.DataFrame)

## 행 인덱싱

In [64]:
df['서울']

KeyError: ignored

In [55]:
# 행 인덱싱을 하고 싶다면
df[:'서울']     # 슬라이싱

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972           2.83

In [56]:
df[1:2]     # 여기는 2 포함 x

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
부산  경상권  3448737  3393191  3512547  3655437           1.63

In [58]:
df['부산':'인천']       # 여기는 인천 포함

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82

In [59]:
df.head(3)

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82

In [60]:
df.tail(3)

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82
대구  경상권  2466052  2431774  2456016  2473990           1.41

## 개별 데이터 인덱싱
- df['열 이름']['행 이름']

In [61]:
df['2015']['서울'], df['2015'][0]

(9904312, 9904312)

### 연습문제 4.1.3

In [63]:
data = {
    "국어": [80, 90, 70, 30],
    "영어": [90, 70, 60, 40],
    "수학": [90, 60, 80, 70],
}
columns = ["국어", "영어", "수학"]
index = ["춘향", "몽룡", "향단", "방자"]
df = pd.DataFrame(data, index=index, columns=columns)
df

국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  30  40  70

In [68]:
# 1) 수학 점수를 시리즈로
df['수학']      # 이게 전통적인 방법

춘향    90
몽룡    60
향단    80
방자    70
Name: 수학, dtype: int64

In [69]:
df.수학     # 이렇게도 나타낼 순 있음

춘향    90
몽룡    60
향단    80
방자    70
Name: 수학, dtype: int64

In [70]:
# 2) 국어, 영어 점수를 데이터프레임으로
df[['국어', '영어']]

국어  영어
춘향  80  90
몽룡  90  70
향단  70  60
방자  30  40

In [71]:
# 3) 평균을 새로운 열로 추가
data = {
    "국어": [80, 90, 70, 30],
    "영어": [90, 70, 60, 40],
    "수학": [90, 60, 80, 70],
    "평균": [87, 75, 70, 40]
}
columns = ["국어", "영어", "수학", "평균"]
index = ["춘향", "몽룡", "향단", "방자"]
df = pd.DataFrame(data, index=index, columns=columns)
df

국어  영어  수학  평균
춘향  80  90  90  87
몽룡  90  70  60  75
향단  70  60  80  70
방자  30  40  70  40

In [72]:
data = {
    "국어": [80, 90, 70, 30],
    "영어": [90, 70, 60, 40],
    "수학": [90, 60, 80, 70],
}
columns = ["국어", "영어", "수학"]
index = ["춘향", "몽룡", "향단", "방자"]
df = pd.DataFrame(data, index=index, columns=columns)
df

국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  30  40  70

In [73]:
df. values

array([[80, 90, 90],
       [90, 70, 60],
       [70, 60, 80],
       [30, 40, 70]])

In [76]:
np.mean(df.values, axis=1).round(1)

array([86.7, 73.3, 70. , 46.7])

In [77]:
df['평균'] = np.mean(df.values, axis=1).round(1)
df

국어  영어  수학    평균
춘향  80  90  90  86.7
몽룡  90  70  60  73.3
향단  70  60  80  70.0
방자  30  40  70  46.7

In [79]:
df.mean(axis=1)     # df에도 자체적 평균 구하는 식이 있음. 추후 배울 예정

춘향    86.675
몽룡    73.325
향단    70.000
방자    46.675
dtype: float64

In [86]:
# 4) 방자 영어점수를 80점으로 수정
del df['평균']
df['영어'][3] = 80
df['평균'] = np.round(df.mean(axis=1), 1)
df

국어  영어  수학    평균
춘향  80  90  90  86.7
몽룡  90  70  60  73.3
향단  70  60  80  70.0
방자  30  80  70  60.0

In [89]:
# 5) 춘향의 점수를 데이터프레임으로
df[0:1]

국어  영어  수학    평균
춘향  80  90  90  86.7

In [90]:
df[:'춘향']

국어  영어  수학    평균
춘향  80  90  90  86.7

In [93]:
df.head(1)          # 중간에 있는 값은 못 빼온다함

국어  영어  수학    평균
춘향  80  90  90  86.7

In [94]:
df.T[['춘향']]

춘향
국어  80.0
영어  90.0
수학  90.0
평균  86.7

In [96]:
df.head(3).tail(2)      # head사용 중간에 있는 값 가져오기

국어  영어  수학    평균
몽룡  90  70  60  73.3
향단  70  60  80  70.0

In [98]:
# 행 추가 T 이용- 열 추가 후- 다시 T

In [102]:
# 6) 향단의 점수를 시리즈로
df.T['향단']

국어    70.0
영어    60.0
수학    80.0
평균    70.0
Name: 향단, dtype: float64

In [103]:
df['영어']['방자']

80