# Numerical Python(Numpy) - Part1

In [1]:
# de facto standard (사실상의 표준)
import numpy as np

In [2]:
a = [1, 2, 3]
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [3]:
list(map(lambda x: 3*x, a))

[3, 6, 9]

In [4]:
b = np.array([1,2,3])
b * 3

array([3, 6, 9])

## 1. Numpy Dimensional array

In [6]:
a = np.array([1,4,5,8], float)
a

array([1., 4., 5., 8.])

In [7]:
type(a)

numpy.ndarray

In [9]:
a.dtype, a.shape        # shape 데이터가 몇 차원이냐 array([1., 4., 5., 8.] 1차원임. 개수 4개

(dtype('float64'), (4,))

In [10]:
# [[1,2,3],[4,5,6]]일 시 2차원(2, 3)

In [11]:
# 리스트는 다양한 타입 [정수, 실수 등] 가능하나 넘파이는 빠른 계산이 목적이여서 통일성을 강조한다
# 실수면 실수로만 가능

## 2. Array shape

In [13]:
# Vector(1차원)
vec = np.array([1,4,5,8])
vec.shape

(4,)

In [16]:
# Matrix(2차원)
matrix = np.array([[1,2,3], [4,5,6]])
print(matrix.shape)
matrix

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
print(matrix)

[[1 2 3]
 [4 5 6]]


In [20]:
# Tensor(3차원)
tensor = np.arange(1,25).reshape(2,3,4)
print(tensor)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [24]:
vec.shape, matrix.shape, tensor.shape

((4,), (2, 3), (2, 3, 4))

In [26]:
# element의 갯수
vec.size, matrix.size, tensor.size

(4, 6, 24)

In [36]:
# data type
# float32: 32bit로 표시 - single precision
# float64: 64bit로 표시 - precision
a = np.array([1,2,3], dtype=np.float32)
a

array([1., 2., 3.], dtype=float32)

In [30]:
a = np.array([1,2,3], np.float32)
a

array([1., 2., 3.], dtype=float32)

In [32]:
b = np.array([1,2,3], dtype=np.int16)
b

array([1, 2, 3], dtype=int16)

### reshape

In [33]:
matrix.shape

(2, 3)

In [34]:
matrix.reshape(6,)

array([1, 2, 3, 4, 5, 6])

In [35]:
matrix.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
# -1은 numpy가 알아서 맞춰줌 (단, size가 동일)
matrix.reshape(-1,)

array([1, 2, 3, 4, 5, 6])

In [39]:
matrix.reshape(3, -1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
matrix.reshape(3, -1).shape

(3, 2)

In [43]:
tensor.reshape(4,-1).shape

(4, 6)

In [44]:
matrix.reshape(-1,)

array([1, 2, 3, 4, 5, 6])

In [45]:
matrix.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6]])

In [46]:
matrix.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

### flatten

In [54]:
tensor.reshape(-1,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [49]:
tensor.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

## 3. Indexing & Slicing

Indexing

In [50]:
tensor.shape

(2, 3, 4)

In [51]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
matrix[0][1]

2

In [53]:
matrix[0,1]

2

In [55]:
tensor[1,1,2]

19

### slicing

In [56]:
b = np.arange(16).reshape(4,-1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [57]:
# 5,6,9,10
b[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [59]:
# 1,3,9,11
b[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [62]:
# X는 앞의 3열, y는 마지막 열
X, y = b[:, :-1], b[:, -1]
X.shape, y.shape

((4, 3), (4,))